name: Release RubyGem
on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Build gem with version from tag
        env:
          TAG_NAME: ${{ github.ref_name }}   # e.g. "v0.0.3"
        run: |
          VER="${TAG_NAME#v}"
          echo "Building version: $VER"
          GEM_VERSION="$VER" gem build qawolf-socket-rubygem.gemspec
          ls -l qawolf-socket-rubygem-*.gem

          VER="$VER" ruby -e '
            require "rubygems/package"
            file = Dir["qawolf-socket-rubygem-*.gem"][0]
            spec = Gem::Package.new(file).spec
            abort("mismatch #{spec.version} != #{ENV["VER"]}") unless spec.version.to_s == ENV["VER"]
            puts "OK #{spec.name} #{spec.version}"
          '

      - name: Publish to RubyGems
        run: |
          mkdir -p ~/.gem
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          gem push qawolf-socket-rubygem-*.gem
