# .github/workflows/release-rubygem.yml
name: Release RubyGem
on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Sync gemspec version from tag
        run: |
          VER="${GITHUB_REF_NAME#v}"
          sed -i -E 's/(spec\.version\s*=\s*")[^"]+(")/\1'"$VER"'\2/' qawolf-socket-rubygem.gemspec
          ruby -e 'spec=Gem::Specification.load("qawolf-socket-rubygem.gemspec"); abort("bad version") unless spec.version.to_s == ENV["VER"]; puts "Gem version=#{spec.version}"' VER="$VER"

      - name: Build gem
        run: gem build qawolf-socket-rubygem.gemspec

      - name: Publish to RubyGems
        run: |
          mkdir -p ~/.gem
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          gem push qawolf-socket-rubygem-*.gem

          gem push qawolf-socket-rubygem-*.gem
